config/routes.rb
TaskManagerProject::Application.routes.draw do
  root :to => 'pages#home'
  
  post "dashboard" => 'pages#update'
  get "dashboard" => 'pages#dashboard', :as => "dashboard"
  
  # Login/Logout Routes
  get "logout" => 'logins#destroy', :as => "logout"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  post "/tasks/:id/add-category" => 'tasks#add_category', :as => "add_category"
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-comment" => 'tasks#add_comment', :as => "add_comment"
  
  resources :users, :tasks, :categories, :projects, :activities
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :deadline, :name, :project_id, :categories, :order

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :users
  has_many :comments
  
  scope :is_complete, where(:complete => true)
  scope :is_not_complete, where(:complete => false)
  
  validate :deadline_is_date?
  validate :name, :order, presence: true
  
  belongs_to :project
  
  # Changes the boolean saved in the "complete" column to a more user-friendly string
  #
  # Returns a user-friendly string describing whether the task is stored as complete or not
  def completed
    complete? ? "complete" : "not complete"
  end

  # Validates that the user's input for deadline is a valid date
  #
  # Returns an error if it is not a valid date, otherwise it allows the new task to be created
  def deadline_is_date?
    if !deadline.is_a?(Date)
      errors.add(:deadline, 'must be a valid date') 
    end
  end
end

app/controllers/tasks_controller.rb
require 'pony'

class TasksController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show]
  
  @@task_new = "You have a new saved task! Click the edit link to assign it to a user."
  @@task_alert = "Oops! Something went wrong! Please try again."
  @@add_category = "The category has been successfully added to this task."
  @@comment = "New comment saved! Way to go."
  @@comment_a = "You must be logged in to do leave a comment."
  @@task_u = "Task updated! Way to go."
  @@task_d = "Your task has been deleted."
  
  def index
    @tasks = Task.all
    @tasks.sort! { |a, b| a.order <=> b.order }
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @user = User.first
    
    if @task.save
      track_activity @task
      @user.send_task_email(@task)
      redirect_to dashboard_path(@task.id), :notice => @@task_new
    else
      flash[:alert] = @@task_alert
      render "new"
    end
  end

  def edit
    @task = Task.find(params[:id])

    @projects = Project.all

    @categories = Category.all
    @users = User.all
  end

  def add_category
    @task = Task.find(params[:id])

    @category = Category.find(params[:task][:categories].to_i)

    if @task.categories.include? @category
      render "show"
    else
      @task.categories << @category

      redirect_to task_path(@task.id), :notice => @@add_category
    end
  end

  def add_user
    @task = Task.find(params[:id])
    @user = User.find(params[:task][:users].to_i)

    if @task.users.include? @user
      render "show"
    else
      @task.users << @user
      @user.send_task_email(@task)

      redirect_to task_path(@task.id), :notice => "The task has been assigned to #{@user.name}."
    end
  end

  def add_comment
    @user = current_user
    @task = Task.find(params[:id])
    @comment = Comment.new(comment_text: params[:comment][:comment_text], user_id: current_user.id, task_id: @task.id)

    if @comment.save

      redirect_to task_path(@task.id), :notice => @@comment
    else
      render "login", :alert => @@comment_a
    end
  end

  def update
    @task = Task.find(params[:id])
    
    if @task.update_attributes(params[:task])
      track_activity @task

      redirect_to task_path(@task.id), :notice => @@task_u
    else
      render "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    Activity.delete_tracked_activities("Task", @task.id)
    @task.delete

    redirect_to dashboard_path, :notice => @@task_d
  end

  def show
    @task = Task.find(params[:id])
    @user = current_user
    @comment = Comment.new
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Edit page for <%= @task.name %></h1>

<div class="errors">
  <% @task.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
</div>

<%= form_for @task do |f| %>
  <p>Task name: <%= f.text_field :name %></p>  
  <p>Deadline (YYYY-MM-DD): <%= f.text_field :deadline%></p>  
  <p>Complete? <%= f.check_box :complete%></p>  
  <p>Project: <%= f.collection_select(:project_id, @projects, :id, :name )%></p>
  <p>Order: <%= f.text_field(:order) %>
  <p><%= f.submit %></p>
<% end %>

</br>

<%= form_for(@task, :url => add_category_path, :method => "post", :action => "update") do |f| %>
  <p>Category: <%= f.collection_select(:categories, @categories, :id, :name )%><%= f.submit "Add category" %></p>
<% end %>

<%= form_for(@task, :url => add_user_path, :method => "post") do |f| %>
  <p>Assigned to: <%= f.collection_select(:users, @users, :id, :email )%><%= f.submit "Assign" %></p>
<% end %>

<p>Would you like to delete "<%= @task.name %>" from your profile? This action can not be undone: <%= button_to "Delete", {action: "destroy", id: @task.id }, method: :delete, data: { confirm: "Are you sure?" }%>

app/views/tasks/index.html.erb
<div id="tasks_index_page">
  <h1>All Tasks</h1>

  <table>
    <tr>
      <td>Order</td>
      <td>Task Name</td>
      <td>Deadline</td>
      <td>Status</td>
      <td>Project:</td>
      <td>Assigned to:</td>
    </tr>
    
    <% @tasks.each do |t| %>
  
      <tr>
    	  <td><%= t.order %></td>
        <td><%= link_to(t.name, task_path(t.id)) %></td>
        <td><%= t.deadline %></td>
        <td><%= t.completed.capitalize %></td>
	
    	<% if t.project %>
        <td><%= link_to(t.project.name, project_path(t.project.id)) %></td>
    	<% else %>
        <td>&nbsp;</td>
    	<% end %>
  
    	<% if t.users != [] %>
        <td>
          <% t.users.each do |u| %>
              <%= link_to(u.name, user_path(u.id)) %>
          <% end %></td>
    	<% else %>
        <td>&nbsp;</td>
    	<% end %>
	
        <td><%= link_to("Edit", edit_task_path(t.id)) %></td>
        <td><%= link_to("Delete", task_path(t.id), :method => :delete, data: {confirm: 'Are you sure you want to delete ' + t.name + '?' })%>
		
      </tr>
    <% end %>
  
  </table>
  
  <div id="tasks_index_links">
    <p><%= link_to("New Task", new_task_path) %></p>
  </div>
  
</div>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<div class="errors">
  <% @task.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
</div>

<%= form_for @task do |f| %>
  <p>Task name: <%= f.text_field :name %></p>  
  <p>Deadline (YYYY-MM-DD): <%= f.text_field :deadline %></p>
  <p>Order/Priority(num): <%= f.text_field :order %></p>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div id="content_container">
  <h1>Show detail page for <%= @task.name %></h1>

  <p>Task name: <%= @task.name %></p>

  <% if @task.project == nil %>
    <p>Not assigned to a project</p>
  <% else %>
    <p>Assigned to Project: <%= @task.project.name %></p>
  <% end %>

  <% if @task.users == [] %>
    <p>Not assigned to a user</p>
  <% else %>
    <p>
      Assigned to: 
      <% @task.users.each do |u| %>
        <%= u.name %></p>
      <% end %>
  <% end %>

  <p>Deadline: <%= @task.deadline %></p>

  <p><%= @task.completed.capitalize %></p>

  <% @task.categories.each do |cat| %>

      <p><%= link_to(cat.name, category_path(cat.id)) %></p>
	
     <% end %>
</div>
     
<% if current_user %> 
  <div id="comment_container">
    <% if @task.comments == [] %>
      <div class="comments">
        <p> No comments on this task. Start the conversation by adding one below. </p>
      </div>
    <% else %>
        <% @task.comments.each do |c| %>
        <div class="comments">
          <p><%= link_to(c.user.email, user_path(c.user.id))%></br>
            <%= simple_format(c.comment_text)%></br>
            <div class="comment_timestamp"><%= c.created_at %></div></p>
        </div>
        <% end %>
    <% end %>
  </div>
    <div id="new_comment_box">  
      <p>New comment:</p>
      <p><%= form_for(@comment, :url => add_comment_path, :method => "post") do |f| %>
        <%= f.text_area :comment_text, size: '73x5' %>
        <%= f.submit %>  
      <% end %></p>
    </div>
<% end %>
   
<p><%= link_to("Edit task", edit_task_path(@task.id)) %></p>