config/routes.rb
TaskManagerProject::Application.routes.draw do
  root :to => 'pages#home'
  
  post "dashboard" => 'pages#update'
  get "dashboard" => 'pages#dashboard', :as => "dashboard"
  
  # Login/Logout Routes
  get "logout" => 'logins#destroy', :as => "logout"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  post "/tasks/:id/add-category" => 'tasks#add_category', :as => "add_category"
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-comment" => 'tasks#add_comment', :as => "add_comment"
  
  resources :users, :tasks, :categories, :projects, :activities
end

app/views/pages/dashboard.html.erb
<div class="adding_tasks">
  
    <h1>Add a new task</h1>

        <%= form_for @task do |f| %>

          <p>Task name: <%= f.text_field :name %></p>
          <p>Deadline (YYYY-MM-DD): <%= f.text_field :deadline%></p>
  
          <%= f.submit %>
  
        <% end %>
       
</div>
  
<div class="users_tasks">
  
  <h1>Current tasks</h1>
  
      <% @tasks.each do |t| %>
        <table>
          <tr>
        	  <td><%= t.order %></td>
            <td><%= link_to(t.name, task_path(t.id)) %></td>
            <td><%= t.deadline %></td>
            <td><%= t.completed.capitalize %></td>
	
        <% if t.project %>
            <td><%= link_to(t.project.name, project_path(t.project.slug)) %></td>
        <% else %>
            <td>&nbsp;</td>
        <% end %>
  
  
        <% if t.users != [] %>
            <td>
              <% t.users.each do |u| %>
                <p><%= link_to(u.name, user_path(u.id)) %></p>
              <% end %>
            </td>
        <% else %>
            <td>&nbsp;</td>
        <% end %>
	
            <td><%= link_to("Edit", edit_task_path(t.id)) %></td>
            <td><%= link_to("Delete", task_path(t.id), :method => :delete, data: {confirm: 'Are you sure you want to delete ' + t.name + '?' })%>
		
          </tr>
        </table>
    <% end %>
     
    <%= button_to "update", {action: "update", id: @task.id } %>

</div>


<div class="activity_feed">
 
 <h1>Recent activity</h1>
    <% @activities.each do |activity| %>
        <p><%= activity.user.name + ' ' + activity.action + 'd ' + activity.trackable_type + ' ' + activity.trackable.name %></p>
    <% end %>

</div>

app/views/pages/home.html.erb
<div id="welcome">
  
  <% @user.errors.full_messages.each do |msg| %>

    <p><%= msg %></p>
  
  <% end %>
  
  
  <h1>Welcome, let's get started..!</h1>
  <h6>Already a user, log in below...</h6>
  
    <%= form_tag login_path do %>

    	<div class="field">
    		<%= label_tag :email %><br />
        <%= text_field_tag :email, params[:email] %>
      </div>

      <div class="field">
        <%= label_tag :password %><br />
        <%= password_field_tag :password %>
      </div>
      
      <div class="field">
      	<%= submit_tag "Log In" %>
      </div>
    
    <% end %>
  
<div id="welcome_2">
  <h6>Or create a new account...</h6>
  
  <%= button_to "New User", {action: "new", :controller=>"users"}, method: :get   %>
  
</div>