config/routes.rb
TaskManagerProject::Application.routes.draw do
  root :to => 'pages#home'
  
  post "dashboard" => 'pages#update'
  get "dashboard" => 'pages#dashboard', :as => "dashboard"
  
  # Login/Logout Routes
  get "logout" => 'logins#destroy', :as => "logout"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  post "/tasks/:id/add-category" => 'tasks#add_category', :as => "add_category"
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-comment" => 'tasks#add_comment', :as => "add_comment"
  
  resources :users, :tasks, :categories, :projects, :activities
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :deadline, :description, :name, :complete, :slug
  
  scope :is_complete, where(:complete => true)
  scope :is_not_complete, where(:complete => false)
  
  validates :name, :slug, presence: true
  validate :deadline_is_date?
  
  has_many :tasks
  
  # Changes the boolean saved in the "complete" column to a more user-friendly string
  #
  # Returns a user-friendly string describing whether the project is stored as complete or not
  def completed
    if complete == true
      "complete"
    else
      "not complete"
    end
  end

  # Validates that the user's input for deadline is a valid date
  #
  # Returns an error if it is not a valid date, otherwise it allows the new project to be created
  def deadline_is_date?
    if !deadline.is_a?(Date)
      errors.add(:deadline, 'must be a valid date') 
    end
  end
  
  def to_param
    slug
  end
  
  def slug
    name.downcase.gsub(" ", "-")
  end

  def create_slug(project)
      slug = project.name.downcase.gsub(" ", "-")
      project.update_attributes(:slug => slug)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  @@new_project = "New project saved! Way to go."
  @@edit_project = "Project updated! Way to go."
  @@delete_project = "Your project has been deleted."
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      @project.create_slug(@project)
      track_activity @project

      redirect_to project_path(@project), :notice => @@new_project
    else
      render "new"
    end
  end

  def edit
    @project = Project.find_by_slug(params[:id])
  end

  def update
    @project = Project.find_by_slug(params[:id])

    if @project.update_attributes(params[:project])
      @project.create_slug(@project)
      track_activity @project

      redirect_to project_path(@project), :notice => @@edit_project
    else
      render "edit"
    end
  end

  def show
    @project = Project.find_by_slug(params[:id])
  end

  def destroy
    @project_id = Project.find_by_slug(params[:id]).id
    @project = Project.find_by_slug(params[:id])

    delete_tracked_projects
    delete_slug(Project)
    redirect_to dashboard_path, :notice => @@delete_project
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div id="edit_project_page">
  <h1>Edit <%= @project.name %></h1>

  <div class="errors">
    <% @project.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>

  <%= form_for @project do |f| %>
  
    <p>Project name: <%= f.text_field :name %></p>
    <p>Description <%= f.text_field :description %></p>
    <p>Deadline (YYYY-MM-DD): <%= f.text_field :deadline %></p>
    <p>Complete? <%= f.check_box :complete%></p>
    <%= f.submit %>
  
  <% end %>

  <p>
    Would you like to delete "<%= @project.name %>" from the application? This action can not be undone:
    <%= link_to 'Delete', project_path(@project), :method => :delete, data: {confirm: 'Are you sure you want to delete ' + @project.name + '?' } %>
  </p>

</div>

app/views/projects/index.html.erb
<div id="projects_page">
  <h1>All Projects</h1>

  <table>
    <tr>
      <td>Project Name</td>
      <td>Deadline</td>
      <td>Status</td>
      <td>Description</td>
    </tr>
	
    <% @projects.each do |project| %>
  
      <tr>
        <td><%= link_to(project.name, project_path(project)) %></td>
        <td><%= project.deadline %></td>
        <td><%= project.completed.capitalize %></td>
        <td><%= project.description %></td>
        <td><%= link_to("Edit", edit_project_path(project))%></td>
        <td><%= link_to("Delete", project_path(project), :method => :delete, data: {confirm: 'Are you sure you want to delete ' + project.name + '?' })%></td>
      </tr>
  
    <% end %>
  
  </table>
  
<div id="projects_link_new">
  <p><%= link_to("New Project", new_project_path) %></p>
</div>

app/views/projects/new.html.erb
<div id="new_project_page">
  
  <h1>Add a new project</h1>

  <div class="errors">
    <% @project.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>

  <%= form_for @project do |f| %>
    <p>Project name: <%= f.text_field :name %></p>
    <p>Description <%= f.text_field :description %></p>
    <p>Deadline (YYYY-MM-DD): <%= f.text_field :deadline %></p>
    <%= f.submit %>
  <% end %>

</div>

app/views/projects/show.html.erb
<div id="project_show_page">
  <h1>Detail page for <%= @project.name %></h1>

  <p><%= @project.completed.capitalize %></p>
  <p><%= @project.deadline %></p>
  <p><%= simple_format(@project.description)%></p>
  <p>Tasks:</br>

      <% @project.tasks.each do |t| %>
        <p><%= link_to(t.name, task_path(t.id))%></p>
      <% end %>

  <p><%= link_to("Edit project", edit_project_path(@project)) %></p>
  
</div>