config/routes.rb
TaskManagerProject::Application.routes.draw do
  root :to => 'pages#home'
  
  post "dashboard" => 'pages#update'
  get "dashboard" => 'pages#dashboard', :as => "dashboard"
  
  # Login/Logout Routes
  get "logout" => 'logins#destroy', :as => "logout"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  post "/tasks/:id/add-category" => 'tasks#add_category', :as => "add_category"
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-user" => 'tasks#add_user', :as => "add_user"
  
  post "/tasks/:id/add-comment" => 'tasks#add_comment', :as => "add_comment"
  
  resources :users, :tasks, :categories, :projects, :activities
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_and_belongs_to_many :tasks, :uniq => true
  
  # validates_uniqueness_of :task_id, :scope => [:category_id]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_filter :authorize
  @@cat_create = "Category has been created."
  @@cat_update = "Category has been updated."
  @@cat_destroy = "Category has been deleted."

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to category_path(@category.id), :notice => @@cat_create
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])

    @tasks = Task.all
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to category_path(@category.id), :notice => @@cat_update
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])

    redirect_to dashboard_path, :notice => @@cat_destroy
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_for @category do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  
  <%= f.submit %>

<% end %>

app/views/categories/index.html.erb
<h1>Categories Home</h1>

<% @categories.each do |c| %>

	<p><%= c.name %></p>
	<p><%= c.description %></p>
	<p><%= link_to('Edit', edit_category_path(c.id)) %></p>
	<p><%= link_to('Delete', category_path(c.id), method: :delete) %>
		
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for @category do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  
  <%= f.submit %>

<% end %>

app/views/categories/show.html.erb
<p><%= @category.name %></p>
<p><%= @category.description %></p>